---
title: "Evaluations of positive and negative stimuli using the Affective Misattribution Procedure (AMP) and self-reports"
subtitle: "Analysis"
author: "Template: Ian Hussey; content: [Student name]"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

# TODO

- Demographics summary
- Analyses
- ...?

```{r, include=FALSE}

# set knit options
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

# disable scientific notation
options(scipen = 999) 

```

# Dependencies

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)

```

# Get data

```{r}

data_processed <- read_csv("../../../data/AMP study/processed/data_processed.csv")

data_processed_after_exclusions <- data_processed |>
  filter(exclude_participant == "include")

```

# Sample descriptives

## Sample size before exclusions

```{r}

data_processed |>
  count() |>
  kable() |>
  kable_classic(full_width = FALSE)

```

## Sample size after exclusions

```{r}

data_processed_after_exclusions |>
  count() |>
  kable() |>
  kable_classic(full_width = FALSE)

```

## Age

```{r}

data_processed_after_exclusions |>
  mutate(age = as.numeric(age)) |>
  summarise(mean_age = mean(age, na.rm = TRUE),
            sd_age = sd(age, na.rm = TRUE)) |>
  mutate_all(.funs = janitor::round_half_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

## Gender

```{r}

data_processed_after_exclusions |> 
  group_by(gender) |> 
  summarise(n = n()) |> 
  mutate(percent = round_half_up((n / sum(n)) * 100, 1)) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

# Descriptive statistics

## Self reported evaluations

```{r}

dat_mean_ratings <- data_processed_after_exclusions |>
  summarise(evaluations_mean = mean(mean_evaluation, na.rm = TRUE),
            evaluations_sd = sd(mean_evaluation, na.rm = TRUE)) |>
  mutate(group = "full sample")

dat_mean_ratings_by_gender <- data_processed_after_exclusions |>
  group_by(group = gender) |>
  summarise(evaluations_mean = mean(mean_evaluation, na.rm = TRUE),
            evaluations_sd = sd(mean_evaluation, na.rm = TRUE))

bind_rows(
  dat_mean_ratings,
  dat_mean_ratings_by_gender
) |>
  select(group, evaluations_mean, evaluations_sd) |>
  mutate_if(is.numeric, round_half_up, digits = 2) |>
  kable() |>
  kable_classic(full_width = FALSE)

```

# Analyses

## Self-reported evalautions

```{r}



```

## Evaluations on the Affect Misattribution Procedure

```{r}



```

# Session info

```{r}

sessionInfo()

```



